### ISSUE TITLE
Runtime configuration file

### ISSUE THREAD

**Issue by lemmingDev** [fatal-bundy/FastIO2KB#2]
Hi

This program is used extensively for making multi-game systems

One huge drawback is that you need to compile multiple custom versions for games that have unchangeable keyboard mappings.

Would you consider updating this program to look for the wanted keyboard mappings from a file at runtime, instead of needing them to be hard-coded?

Unfortunately, the JoeHowse/KB2FastIO fork doesn't allow you to post issues

Thanks for your consideration

**Comment by fatal-bundy** [comment]
Hey LemmingDev

As discussed over Discord i have created a config file version and can be found in the config_model branch until i decide how to move forward with the master branch.

Regards
Corey
